[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tensorflow-privacy-fl"
version = "0.1.0"
description = "Sample-level Differential Privacy with Tensorflow-Privacy in Flower"
authors = [
    { name = "The Flower Authors", email = "hello@flower.ai" },
]
dependencies = [
    "flwr>=1.8.0,<2.0",
    "flwr-datasets[vision]>=0.0.2,<1.0.0",
    "tensorflow-cpu>=2.9.1, != 2.11.1 ; platform_machine == \"x86_64\"",
    "tensorflow-macos>=2.9.1, != 2.11.1 ; sys_platform == \"darwin\" and platform_machine == \"arm64\"",
    "tensorflow-privacy == 0.9.0"
]

[tool.hatch.build.targets.wheel]
packages = ["."]
