[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "testjax"
version = "1.0.0"
description = ""
authors = [
    { name = "The Flower Authors", email = "hello@flower.ai" },
]
license = {text = "Apache License (2.0)"}
dependencies = [
    "flwr[simulation]>=1.8.0,<2.0",
    "jax==0.4.26",
    "jaxlib==0.4.26",
    "scikit-learn==1.4.2",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[flower]
publisher = "javier"

[flower.components]
serverapp = "testjax.server:app"
clientapp = "testjax.client:app"
